### ISSUE TITLE
Rendering `ecr` files

### ISSUE THREAD

**Issue by drujensen** [mosop/teeplate#1]
Is there a way to render `ecr` files?

**Comment by mosop** [comment]
Currently, all files ending with ".ecr" are automatically recognized as template files. If you want to write out ecr files, add ".ecr" to the filenames. For example, "file.ecr.ecr", instead of "file.ecr".

**Comment by drujensen** [comment]
Thanks for the response.  

How do you tell it that you want certain tags to be processed and other tags to not be processed?  Is there a way to escape the tags?

<%= # to be processed by .ecr.ecr %>
<%= # to be passed through to .ecr  %>

**Comment by mosop** [comment]
Teeplate just passes ".ecr" files to the standard ECR processor. I'm not familiar with ECR, but how is this?

```
<%= "<" %>%= @to_be_passed_through_to_ecr %>
```

rendered as:

```
<%= @to_be_passed_through_to_ecr %>
```

**Comment by drujensen** [comment]
clever!  Thanks.  I will give that a try.
