### ISSUE TITLE
Append Option

### ISSUE THREAD

**Issue by drujensen** [mosop/teeplate#2]
Add the ability to append to the end of a file instead of skip/overwrite it.

**Comment by drujensen** [comment]
I need this for only specific files in the templates.  Specifically, I need to append to the config/routes.cr file.

maybe a file naming convention?  If the file name ends with a + then it will append instead of overwrite?

**Comment by mosop** [comment]
I think it's a rare case. Instead of "append", how is "custom rendering" like this?

```crystal
class Template < Teeplate::FileTree
  directory "/path/to/template"

  def overwrite_file(out_file, ...)
    if out_file == "config/routes.cr"
      render_routes out_file, ...
    else
      super
    end
  end

  def overwrite_routes(out_file, ...)
    # ...
  end
end
```

**Comment by mosop** [comment]
Or, tell me more details about your story if you can.

**Comment by drujensen** [comment]
@mosop Thanks for your response!

We are using two of your libraries to build a rails like generator for Kemalyst.  They have been a huge help to this project.  https://github.com/TechMagister/kemalyst-generator

To generate a resource, we need to inject the routes into the /config/routes.cr file.  Your suggestion of overwriting the method should work fine. You are correct that this is a rare case and something we can handle in the Template class.  

Thanks for the suggestion.

**Comment by mosop** [comment]
Thank you.

* How does the generator's user append a new route into the routes.cr?

* Can I see the routes.cr samples? I want to see:
  * a typical state before appending
  * a typical state after appending

**Comment by drujensen** [comment]
Here is the `routes.cr` template when you create a new Kemalyst project:  https://github.com/TechMagister/kemalyst-generator/blob/master/src/templates/app/config/routes.cr

Here is the scaffolding to add a new resource to the `routes.cr`:  https://github.com/TechMagister/kemalyst-generator/blob/master/src/templates/scaffold/config/%2Broutes.cr.ecr

I solved this problem by re-opening the `Entry.cr` and looking for a `+` in the filename.  If there is a +, then I strip the `+` and open the file as append:  https://github.com/TechMagister/kemalyst-generator/blob/master/src/templates/entry.cr

Let me know if you have other suggestions on how to solve this.

**Comment by mosop** [comment]
Thank you. I'll think it over. Wait for a while.

**Comment by mosop** [comment]
Hi @drujensen, I added this feature into v0.3.0. It's almost the same as you want; You add a "+" sign into the head of filename and the file is written with "append mode". Try it!

**Comment by drujensen** [comment]
Awesome.  Thanks!
