### ISSUE TITLE
from_collect not rendering ecr before output

### ISSUE THREAD

**Issue by forsbergplustwo** [mosop/teeplate#3]
Thanks for the great tool. In the latest version 0.4.3 you added a new method `from_collect` so that it's possible to add multiple paths to the input of files. However, when using that method, the files are no longer being ecr rendered before output.

```
require "teeplate"

module Kemalyst::Generator
  class App < Teeplate::FileTree

    @name : String

    def initialize(@name)
    end
  end
end
```
```
        puts "Generating App #{name} in #{directory} with #{view_handler}"
        app = App.new(@name)
        app.collect_from "#{__DIR__}/app"
        app.collect_from "#{__DIR__}/views/#{view_handler}/#{template}"
        app.render(directory, list: true)
```

Results in the following (list shortened to show the relevant files only):
````
new       bin/sentry.cr.ecr
new       config/session.cr.ecr
new       README.md.ecr
new       shard.yml.ecr
new       src/{{name}}.cr
````

If done the without using `from_collect` then it does ecr render the files before output.

```
require "teeplate"

module Kemalyst::Generator
  class App < Teeplate::FileTree
    directory "#{__DIR__}/app"

    @name : String

    def initialize(@name)
    end
  end
end
```
```
        puts "Generating App #{name} in #{directory} with #{view_handler}"
        app = App.new(@name)
        app.render(directory, list: true)
```
```
Generating App newapp in ./newapp with slang
new       bin/sentry.cr
new       config/session.cr
new       README.md
new       shard.yml
new       src/newapp.cr
```

Any pointers? 

I want to propose a PR to kemalyst-generator project so the user can choose between slang and ecr view files when generating app, and this new method is perfect if I can get the method working 😉 

Many thanks

**Comment by mosop** [comment]
Unfortunately, Crystal ECR is a bit less flexible than the other languages such as ERB for dynamically parsing and rendering templates. Because we need to statically embed ECR templates into our source code in compile time. (ECR is very fast instead.)

I'd like to support more languages in the future version but it may be not soon.

**Comment by forsbergplustwo** [comment]
Thanks for the quick reply, much appreciated :) I'll do some more research to see if I can work around it.
